defmodule ObanWeb.PdfController do
  use ObanWeb, :controller

  def gen_pdf(conn, _params) do
    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Test PDF</title>
    </head>
    <body>
      <h1>Hello World</h1>
      <p>This is a test PDF generated by ChromicPDF.</p>
    </body>
    </html>
    """

    case ChromicPDF.print_to_pdf({:html, html_content}) do
      {:ok, pdf_content} ->
        # Crear directorio pdfs si no existe
        pdf_dir = Path.join(File.cwd!(), "pdfs")
        File.mkdir_p!(pdf_dir)

        # Generar nombre de archivo con timestamp
        timestamp = DateTime.utc_now() |> DateTime.to_unix()
        filename = "output_#{timestamp}.pdf"
        filepath = Path.join(pdf_dir, filename)

        # Guardar el PDF (usar modo binario para evitar corrupción)
        File.write!(filepath, pdf_content, [:binary])

        # También devolver el PDF al navegador
        conn
        |> put_resp_content_type("application/pdf")
        |> put_resp_header("content-disposition", "inline; filename=\"#{filename}\"")
        |> put_resp_header("content-length", "#{byte_size(pdf_content)}")
        |> send_resp(200, pdf_content)

      {:error, reason} ->
        conn
        |> put_resp_content_type("application/json")
        |> put_status(503)
        |> json(%{
          success: false,
          error: "PDF Generation Error",
          reason: inspect(reason)
        })
    end
  end
end
